
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-register-deploy
  labels:
    app: parking-register-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-register-service
  template:
    metadata:
      name: parking-register-service
      labels:
        app: parking-register-service
    spec:
      containers:
        - name: parking-register-service
          image: yoon741/register:v5
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret  # Secret 이름
                  key: MYSQL_USER  # Secret 키
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-payment-service
spec:
  replicas: 1  # 불필요한 추가 생성 방지를 위해 replicas 수를 1로 설정
  selector:
    matchLabels:
      app: msa-payment-service
  template:
    metadata:
      labels:
        app: msa-payment-service
    spec:
      containers:
        - name: msa-payment-service
          image: ashashrain/parking-payment-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"


---

apiVersion: v1
kind: Service
metadata:
  name: parking-register-service
spec:
  selector:
    app: parking-register
  ports:
    - port: 8000
      protocol:  TCP
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: msa-payment-service
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: msa-payment-service

---










